# Generated by Django 2.0.5 on 2020-04-14 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=100)),
                ('who', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('answers', jsonfield.fields.JSONField(default=dict)),
                ('ic', models.CharField(max_length=50)),
                ('criterions', jsonfield.fields.JSONField(default=dict)),
                ('preferences', jsonfield.fields.JSONField(default=dict)),
                ('age', models.CharField(max_length=100)),
                ('time_emp', models.CharField(max_length=100)),
                ('time_xp', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Groups_group', to='groups.Groups', verbose_name='Grupo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('objective', models.CharField(max_length=500)),
                ('data_to_end', models.DateTimeField(null=True)),
                ('Groups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.Groups', verbose_name='Grupo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
